version: "3"
services:
  python_app:
    container_name: "python_app"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python_ml:3.7.2
    volumes:
    - ./src:/python_ML_test/src
    - ./test:/python_ML_test/test
    command: /bin/bash
    ports:
      - 80:80
    tty: true